// v0.7.1 场景补写·朵朵线（三原则：P1揭示人物/P2推进张力/P3改变世界质感）
export const ADD_DD = {
  'duoduo_s1_meet/gate': [
    { text: '隔着篱笆把罐头推过去，不靠太近',
      outcomes: [{ text: '你没有开门，也没有靠近——罐头从栅栏缝里滚过去，停在离她一步远的地方。她扑过来抱住罐头的样子，像抱住整个旧世界。',
        effects: { sanity: 2, relNpc: 'kid', relDelta: 3, loseItems: [{ itemId: 'food_canned', count: 1 }], skillXp: { survival: 5 } }, goto: 'name' }] },
    { text: '先观察她：有没有伤，身后有没有跟着东西',
      requires: { skillLevel: { survival: 1 } },
      outcomes: [{ text: '你扫了一眼——袖口没有血渍，脚边只有一小串朝外的脚印。她是自己走到这里的，没有被跟。这个判断让你松了半口气。',
        effects: { sanity: 2, skillXp: { knowledge: 6, survival: 3 } }, goto: 'name' }] },
  ],
  'duoduo_s1_meet/name': [
    { text: '反问她：「那你叫什么？总得公平交易」',
      outcomes: [{ text: '她一下子挺直了腰板，得意得像打了胜仗：「朵朵！花朵的朵！我妈妈说的，人多的地方花就多！」——这是雾降之后，你听到的第一句完整的大话。',
        effects: { relNpc: 'kid', relDelta: 4, setFlags: ['dd_name_swap'], skillXp: { social: 6 } } }] },
    { text: '报一半留一半：「叫我小木就行」',
      outcomes: [{ text: '「真小气。」她嘟着嘴评价，但还是认真重复了一遍：「小木哥哥。」——留了余地，也留了一点罪过感。你决定以后找个机会补全它。',
        effects: { sanity: 1, skillXp: { knowledge: 3 } } }] },
  ],
  'duoduo_s1_meet/promise': [
    { text: '把旧外套披到她肩上，再看她走进雾里',
      requires: { items: [{ itemId: 'mat_cloth', count: 1 }] },
      outcomes: [{ text: '毛衣大了两号，外套更大。她在雾边缘回身冲你挥手，袖子甩得老长，像一只终于暖和过来的、笨拙的小兽。',
        effects: { relNpc: 'kid', relDelta: 5, loseItems: [{ itemId: 'mat_cloth', count: 1 }], skillXp: { social: 5 } } }] },
    { text: '教她一句暗号：「夜枭叫两声，就是我」',
      outcomes: [{ text: '她学得极快，两声婉转的口哨居然真有七分像。「记住喽！」她拍了拍胸口，「听到夜枭，我就知道是哥哥！」——在这片吞掉声音的雾里，你们有了一条私有的频道。',
        effects: { relNpc: 'kid', relDelta: 4, setFlags: ['dd_signal'], skillXp: { knowledge: 4, social: 3 } } }] },
  ],
  'duoduo_s1_meet/repent': [
    { text: '天不亮就把双份食物放上石阶',
      outcomes: [{ text: '你没等到人。食物在石阶上放了一整天，傍晚回来时少了一角——被野猫叼过的牙印，很小，也很清楚。你还是换了新的一份压上去。',
        effects: { sanity: 3, skillXp: { social: 4 } } }] },
  ],
  'duoduo_s2_frog/gift': [
    { text: '削一支炭笔挂在篱笆尖上',
      outcomes: [{ text: '第二天清晨炭笔就不见了，篱笆上多了一张歪歪扭扭的画：一个大人和一个小人，手拉手，太阳画得比房子大。——这画风你在哪儿见过似的，想了一下，没想起来。',
        effects: { relNpc: 'kid', relDelta: 3, skillXp: { craft: 4 } } }] },
  ],
  'duoduo_s2_frog/tea': [
    { text: '举起纸青蛙：「这补丁缝得比我的手艺强」',
      outcomes: [{ text: '「当然啦！」她骄傲地炸了毛，随即又不好意思地小声说，「……针是我偷看妈妈用的学的。扎了三次手才缝上的。」——她说到「妈妈」的时候，声音轻了一瞬，像踩过一片薄冰。',
        effects: { relNpc: 'kid', relDelta: 4, skillXp: { social: 5 } } }] },
  ],
  'duoduo_s2_frog/close': [
    { text: '在频道匿名回一句：「孩子没事，有人照应」',
      outcomes: [{ text: '九千人的沉默里，几分钟后浮上来一个孤零零的「👍」。就一个字，没有人接话。但你关掉频道时发现，自己的肩膀松下来了——有些话不是说给九千人的，是说给自己的。',
        effects: { sanity: 4, setFlags: ['dd_vouched'], skillXp: { social: 6 } } }] },
  ],
  'duoduo_s3_letters/book': [
    { text: '拿浆果当奖品，认对一个给一颗',
      requires: { items: [{ itemId: 'food_berry', count: 3 }] },
      outcomes: [{ text: '她的学习效率高得吓人——为了浆果，「人」「口」「手」半小时拿下，连「伞」这种复杂的都要抢答。最后你不得不宣布「今天库存告罄」，她才意犹未尽地舔舔手指。',
        effects: { relNpc: 'kid', relDelta: 4, loseItems: [{ itemId: 'food_berry', count: 3 }], skillXp: { knowledge: 5, social: 3 } }, goto: 'read' }] },
  ],
  'duoduo_s3_letters/read': [
    { text: '故意写错一个字让她来抓',
      outcomes: [{ text: '她瞪大眼睛盯了半天，突然尖叫：「错啦！『火』这一点是往右的！」然后像个小老师一样板着脸纠正你。你挨训挨得心服口服——会挑错，才是真的学会了。',
        effects: { relNpc: 'kid', relDelta: 3, sanity: 3, skillXp: { social: 4 } } }] },
  ],
  'duoduo_s3_letters/dusk': [
    { text: '把残页夹回课本：「等你认全字，自己念」',
      outcomes: [{ text: '她抱着课本愣了几秒，然后用力点头：「好！那我明天多认十个！」——一张地图变成了一个目标。有时候希望不用很大，够一个孩子踮脚去够就行。',
        effects: { relNpc: 'kid', relDelta: 3, setFlags: ['dd_map_promise'], skillXp: { social: 4 } } }] },
  ],
  'duoduo_s3_letters/sad': [
    { text: '沿篱笆外找一圈，看她脚印的去向',
      requires: { skillLevel: { survival: 1 } },
      outcomes: [{ text: '泥地上那串小脚印朝东，步幅均匀，没有犹豫和回头——她是自己决定走的，不是被拖走的。这个事实说不上安慰，但至少，你不必再想象最坏的那种可能。',
        effects: { sanity: -2, skillXp: { survival: 4, knowledge: 5 } } }] },
  ],
  'duoduo_s4_bear/hug': [
    { text: '往她碗里也拨了半勺热的',
      outcomes: [{ text: '「我有吗？」她指着自己的鼻子，难以置信。你把碗塞过去，她捧着吹了半天凉气，喝一口，抬头看你一眼，再喝一口——那样子像在确认这不是梦。',
        effects: { relNpc: 'kid', relDelta: 5, skillXp: { social: 5 } } }] },
  ],
  'duoduo_s4_bear/late': [
    { text: '把搜来的半截红毛线单独收进内袋',
      outcomes: [{ text: '不知道为什么，你把它和急救包放在了一起。万一呢。万一哪天有个一边高一边低的耳朵需要系上一圈红毛线呢。——「以防万一」，是末世里最温柔的病。',
        effects: { sanity: 2, setFlags: ['dd_yarn_kept'], skillXp: { craft: 3 } } }] },
  ],
  'duoduo_s5_play/knock': [
    { text: '改玩室内捉迷藏，输的人洗碗',
      outcomes: [{ text: '一间小木屋能藏哪儿？窗帘后、床底、柴堆缝。她藏了三次，三次都在憋笑；你找了三次，三次都「找了很久」。最后她赢了两局，洗碗洗得叮当响，快乐得像打赢了一场战争。',
        effects: { sanity: 6, relNpc: 'kid', relDelta: 4, skillXp: { social: 6 } } }] },
  ],
  'duoduo_s5_play/after': [
    { text: '把这个秘密写进日记，锁进抽屉',
      outcomes: [{ text: '笔尖落在纸上：「半夜，雾薄一线。两个人知道的事，比一个人重。」写完你犹豫了一下，又添了半句：「希望她永远有秘密可讲。」',
        effects: { sanity: 3, setFlags: ['dd_secret_journaled'], skillXp: { knowledge: 5 } } }] },
  ],
  'duoduo_s6_crisis/barn': [
    { text: '学一声夜枭叫——你们约好的暗号',
      requires: { flags: ['dd_signal'] },
      outcomes: [
        { weight: 85, text: '黑暗里，哭声戛然而止。三秒死寂之后，仓深处传来两声短促的叩指——她还记着。整场灾祸里，你们第一次踩在了同一个节拍上。',
          effects: { setFlags: ['barn_quiet'], sanity: 3, skillXp: { knowledge: 4 } }, goto: 'shadow' },
        { weight: 15, text: '叩指声慢了半拍才响起。第二遍，她才回应。而谷仓最深的黑暗里，有什么东西缓缓地偏了偏头。',
          effects: { sanity: -4 }, goto: 'shadow' },
      ] },
    { text: '踢翻空油桶，让它滚向村东',
      outcomes: [
        { weight: 60, text: '铁桶在石板路上轰隆远去，一声比一声哑。那东西的轮廓迟疑着，朝声响挪了一步——就一步。够了。',
          effects: { setFlags: ['barn_distracted'], hp: -4, skillXp: { combat: 4 } }, goto: 'shadow' },
        { weight: 40, text: '它没有上当。它甚至没有回头看那个桶——它只是把歪着的头，慢慢地转向了你这一侧。',
          effects: { sanity: -5 }, goto: 'shadow' },
      ] },
    { text: '贴墙屏息，数它的脚步找出规律',
      requires: { skillLevel: { knowledge: 2 } },
      outcomes: [{ text: '一下……两下……第三下永远是拖音。它移动有三拍的节奏，第三拍必然停顿。恐惧还在，但现在，恐惧有了形状——有形状的东西，就能算计。',
        effects: { setFlags: ['barn_pattern'], sanity: -2, skillXp: { knowledge: 8 } }, goto: 'shadow' }] },
  ],
  'duoduo_s6_crisis/shadow': [
    { text: '数着拍子——第三步它必停顿，就是现在',
      requires: { flags: ['barn_pattern'] },
      outcomes: [
        { weight: 80, text: '一，二，拖音——跑！你们贴着它停顿的间隙穿过去，背后没有脚步声追上来。规律没有骗你，冷静没有背叛你。',
          effects: { sanity: 4, skillXp: { knowledge: 6 } }, goto: 'saved_end' },
        { weight: 20, text: '一，二——它没有第三次停顿。它直接转过了那个不该转的角度。你拽着她撞开后门滚进雨沟，左臂擦掉了一层皮。',
          effects: { hp: -8, sanity: -5 }, goto: 'saved_end' },
      ] },
    { text: '它的注意力还在村东——低声：走',
      requires: { flags: ['barn_distracted'] },
      outcomes: [{ weight: 92, text: '油桶还在远处滚动作响。你们弓着腰贴墙根挪出门洞，自始至终，那个轮廓都没有回过头。引开的每一秒，都是拿命换来的时间。',
        effects: { sanity: 3 }, goto: 'saved_end' }] },
  ],
  'duoduo_s6_crisis/saved_end': [
    { text: '把她汗湿的头发拢到耳后，什么都不问',
      outcomes: [{ text: '她睫毛颤了颤，往毯子里缩得更深了一点，抓着你衣角的手却紧了紧。有些问题不必今晚问，有些答案她还没准备好讲——比如，她为什么会一个人在谷仓边上。',
        effects: { relNpc: 'kid', relDelta: 6, sanity: 5, skillXp: { social: 5 } } }] },
  ],
  'duoduo_s6_crisis/lost_end': [
    { text: '把那罐水，倒在她脚印消失的地方',
      outcomes: [{ text: '水渗进泥里，很快就没了痕迹，像从来没有存在过。你站了一会儿，把空罐子揣回了怀里。——仪式这种东西，不是做给失踪者的，是做给还得活下去的人的。',
        effects: { sanity: -1, skillXp: { social: 3 } } }] },
  ],
  'duoduo_s6_crisis/ignore_end': [
    { text: '那一斧劈下去，卡在木头里拔不出来',
      outcomes: [{ text: '你就保持着劈柴的姿势站着，很久。斧刃啃在木纹里，风一阵一阵掀你的衣角。最后你是跪坐着把斧头晃出来的——膝盖弯下去的那一刻，你自己都没察觉。',
        effects: { sanity: -4 } }] },
  ],
  'duoduo_s7_shelter/eve': [
    { text: '把唯一的床让出来，自己抱被子睡灶边',
      outcomes: [{ text: '她抗议了两句就被你按回床上。半夜你迷迷糊糊睁眼，看见她把被子一角搭在了床沿外——那是朝着灶边的方向。小孩子不会说谢谢，只会把温暖分出去一点点。',
        effects: { relNpc: 'kid', relDelta: 5, sanity: 3, skillXp: { social: 4 } }, goto: 'map' }] },
  ],
  'duoduo_s7_shelter/watch': [
    { text: '握住那只发白的小手：「不止直升机，还有明天」',
      outcomes: [{ text: '她没有抽回手。窗外的长嚎还在继续，可屋里这点温度是真的。「嗯。」她说得很轻，很稳，「明天，后天，大后天。」——孩子学会数日子的时候，就不再是需要被保护的年龄了。',
        effects: { relNpc: 'kid', relDelta: 6, setFlags: ['dd_day_counting'], sanity: 4, skillXp: { social: 5 } } }] },
  ],
  'duoduo_s7_shelter/alone': [
    { text: '把那根树枝削平，刻上两个字：「向东」',
      outcomes: [{ text: '刀尖划过木头的声音在空路上传得很远。向东，有人——也许是给她的，也许是给任何一个往南逃难的人。路标这种东西，立下去的那一刻，就不再只属于你了。',
        effects: { sanity: 3, skillXp: { knowledge: 4, craft: 3 } } }] },
  ],
  'duoduo_s8_dawn/oath': [
    { text: '翻开她的小背包，把水壶灌满塞在最上层',
      requires: { items: [{ itemId: 'water_clean', count: 1 }] },
      outcomes: [{ text: '「重不重？」你问。「不重！」她抢着背起来原地蹦了两下，水壶在包里咕咚作响。——你数过了：包里有吃的、有盖的、有玩的有念想的，现在，还有喝的。',
        effects: { relNpc: 'kid', relDelta: 4, loseItems: [{ itemId: 'water_clean', count: 1 }], skillXp: { survival: 5 } } }] },
  ],
};
